{
 "title": "All in one",
 "description": "All in one dashboard that integrates data from various sources, including Raspberry Pi, Windows systems, PiKVM, Solis inverters, Tuya smart plugs, and more. Visualize system metrics, energy consumption, currency exchange rates, and solar power generation all in one place. ",
 "tags": [
  "Windows Exporter",
  "Prometheus",
  "PromDapter",
  "PiKVM",
  "Node Exporter",
  "Desktop",
  "RPI4",
  "Currency Exporter",
  "Solis Inverter Exporter",
  "Tuya Smart Plug Exporter"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "RPI4 Memory Usage (%)",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes\r\n {job=\"RPI4\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemAvailable_bytes {job=\"RPI4\"}",
     "legendFormat": "Available"
    },
    { "expr": "268435456", "legendFormat": "Reserved" }
   ]
  },
  {
   "title": "Memory History",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "application": { "filter": "" },
     "expr": "hwi_memory_available_mb{category=\"Physical\"} * 1048576",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Available Physical Memory1",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "expr": "hwi_memory_used_mb{category=\"Physical\"} * 1048576",
     "legendFormat": "Used Physical Memory1"
    },
    {
     "application": { "filter": "" },
     "expr": "hwi_virtual_memory_committed_mb * 1048576",
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "legendFormat": "Virtual Memory1",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "expr": "hwi_memory_available_mb{category=\"Virtual\"} * 1048576",
     "legendFormat": "Available Virtual Memory1"
    },
    {
     "expr": "hwi_memory_load{category=\"Physical\"}",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "Memory Clock",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "MHz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hwi_memory_clock_mhz * 2", "legendFormat": "{{sensor}}" }
   ]
  },
  {
   "title": "System Power Metrics",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tuya_consumption_power", "legendFormat": "Power" },
    { "expr": "tuya_consumption_current", "legendFormat": "Current" },
    { "expr": "tuya_consumption_voltage", "legendFormat": "Voltage" }
   ]
  },
  {
   "title": "PiKVM Memory Usage (%)",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes {job=\"PiKVM\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_MemAvailable_bytes {job=\"PiKVM\"}",
     "legendFormat": "Available"
    },
    { "expr": "268435456", "legendFormat": "Reserved" }
   ]
  },
  {
   "title": "Memory Latency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hwi_memory_tcas_t", "legendFormat": "TCAS" },
    { "expr": "hwi_memory_trcd_t", "legendFormat": "TRCD" },
    { "expr": "hwi_memory_trp_t", "legendFormat": "TRP" },
    { "expr": "hwi_memory_tras_t", "legendFormat": "TRAS" }
   ]
  },
  {
   "title": "RPI4 Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_cpu_seconds_total{cpu=\"0\", mode=\"idle\", job=\"RPI4\"}",
     "legendFormat": "RPI4 Uptime"
    }
   ]
  },
  {
   "title": "CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "hwi_core_usage", "legendFormat": "CPU {{coreno}} {{category}}" }
   ]
  },
  {
   "title": "Server Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(time() - windows_system_system_up_time)",
     "legendFormat": "Server Uptime"
    }
   ]
  },
  {
   "title": "CPU Power",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "hwi_cpu_package_power_w", "legendFormat": "{{source}}" }
   ]
  },
  {
   "title": "PiKVM Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_cpu_seconds_total{cpu=\"0\", mode=\"idle\", job=\"PiKVM\"}",
     "legendFormat": "PiKVM Uptime"
    }
   ]
  },
  {
   "title": "RPI4 CPU Frequency",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_cpu_scaling_frequency_hertz {job=\"RPI4\"}",
     "legendFormat": "CPU {{cpu}}"
    }
   ]
  },
  {
   "title": "CPU Frequency",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "rotghz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hwi_core_clock_mhz / 1000", "legendFormat": "CPU {{coreno}}" }
   ]
  },
  {
   "title": "PiKVM CPU Frequency",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_cpu_scaling_frequency_hertz {job=\"PiKVM\"}",
     "legendFormat": "CPU {{cpu}}"
    }
   ]
  },
  {
   "title": "CPU Voltage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hwi_cpu_voltage_v", "legendFormat": "{{sensor}}" }
   ]
  },
  {
   "title": "RPI4 CPU Usage (%)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (cpu) (rate(node_cpu_seconds_total{job=\"RPI4\", mode=\"idle\"}[1m])) * 100)\r\n",
     "legendFormat": "CPU {{cpu}}"
    }
   ]
  },
  {
   "title": "System Temperature (ºC)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "hwi_cpu_tctltdie_c", "legendFormat": "{{source}}" },
    { "expr": "hwi_motherboard_c", "legendFormat": "{{source}}" },
    { "expr": "hwi_gpu_temperature_c", "legendFormat": "{{source}}" },
    { "expr": "hwi_gpu_hot_spot_temperature_c", "legendFormat": "{{source}} Junction" },
    { "expr": "node_thermal_zone_temp", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Currency Exchange Rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "BTC_USD",
     "legendFormat": "{{base_currency}} / {{currency}}"
    },
    {
     "expr": "CNY_USD",
     "legendFormat": "{{base_currency}} / {{currency}}"
    },
    {
     "expr": "EUR_BRL",
     "legendFormat": "{{base_currency}} / {{currency}}"
    },
    {
     "expr": "EUR_USD",
     "legendFormat": "{{base_currency}} / {{currency}}"
    },
    {
     "expr": "GBP_EUR",
     "legendFormat": "{{base_currency}} / {{currency}}"
    },
    {
     "expr": "USD_BRL",
     "legendFormat": "{{base_currency}} / {{currency}}"
    },
    {
     "expr": "BTC_USD",
     "legendFormat": "{{base_currency}} / {{currency}}"
    },
    {
     "expr": "CNY_USD",
     "legendFormat": "{{base_currency}} / {{currency}}"
    },
    {
     "expr": "EUR_BRL",
     "legendFormat": "{{base_currency}} / {{currency}}"
    },
    {
     "expr": "EUR_USD",
     "legendFormat": "{{base_currency}} / {{currency}}"
    },
    {
     "expr": "GBP_EUR",
     "legendFormat": "{{base_currency}} / {{currency}}"
    },
    {
     "expr": "USD_BRL",
     "legendFormat": "{{base_currency}} / {{currency}}"
    }
   ]
  },
  {
   "title": "PiKVM CPU Usage (%)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (cpu) (rate(node_cpu_seconds_total{job=\"PiKVM\", mode=\"idle\"}[1m])) * 100)\r\n\r\n",
     "legendFormat": "CPU {{cpu}}"
    }
   ]
  },
  {
   "title": "GPU / VRAM Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "hwi_gpu_d3d_usage", "legendFormat": "{{sensor}}" },
    {
     "expr": "hwi_gpu_d3d_memory_dedicated_mb",
     "legendFormat": "{{sensor}}"
    },
    {
     "expr": "hwi_gpu_d3d_memory_dedicated_mb",
     "legendFormat": "Axis"
    }
   ]
  },
  {
   "title": "GPU / VRAM Frequency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "MHz" } },
   "targets": [
    { "expr": "hwi_gpu_clock_mhz", "legendFormat": "{{sensor}}" },
    { "expr": "hwi_gpu_memory_clock_mhz", "legendFormat": "{{sensor}}" }
   ]
  },
  {
   "title": "GPU Power",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "hwi_gpu_ppt_w", "legendFormat": "{{source}}" }
   ]
  },
  {
   "title": "GPU Voltage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "V" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hwi_gpu_core_voltage_v", "legendFormat": "{{sensor}}" }
   ]
  },
  {
   "title": "Energy Generation",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "inverter_power", "legendFormat": "Current" },
    { "expr": "inverter_energy_today", "legendFormat": "Daily" },
    { "expr": "inverter_energy_total", "legendFormat": "Total" }
   ]
  },
  {
   "title": "GPU Fan",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hwi_gpu_fan_rpm", "legendFormat": "{{sensor}}" },
    { "expr": "hwi_gpu_fan", "legendFormat": "{{sensor}}" }
   ]
  },
  {
   "title": "Partition Usage (%)",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (windows_logical_disk_free_bytes{volume=\"C:\"} / windows_logical_disk_size_bytes{volume=\"C:\"})*100",
     "legendFormat": "{{volume}}"
    },
    {
     "expr": "100 - (windows_logical_disk_free_bytes{volume=\"D:\"} / windows_logical_disk_size_bytes{volume=\"D:\"})*100",
     "legendFormat": "{{volume}}"
    },
    {
     "expr": "100 - (windows_logical_disk_free_bytes{volume=\"E:\"} / windows_logical_disk_size_bytes{volume=\"E:\"})*100",
     "legendFormat": "{{volume}}"
    },
    {
     "expr": "100 - (windows_logical_disk_free_bytes{volume=\"F:\"} / windows_logical_disk_size_bytes{volume=\"F:\"})*100",
     "legendFormat": "{{volume}}"
    },
    {
     "expr": "100 - (windows_logical_disk_free_bytes{volume=\"G:\"} / windows_logical_disk_size_bytes{volume=\"G:\"})*100"
    },
    {
     "expr": "100 - (windows_logical_disk_free_bytes{volume=\"H:\"} / windows_logical_disk_size_bytes{volume=\"H:\"})*100"
    },
    {
     "expr": "100 - (windows_logical_disk_free_bytes{volume=\"I:\"} / windows_logical_disk_size_bytes{volume=\"I:\"})*100"
    },
    {
     "expr": "100 * (\r\n  sum(node_filesystem_size_bytes{job=\"RPI4\", fstype=\"zfs\"})\r\n  - sum(node_filesystem_free_bytes{job=\"RPI4\", fstype=\"zfs\"})\r\n) / sum(node_filesystem_size_bytes{job=\"RPI4\", fstype=\"zfs\"})\r\n",
     "legendFormat": "NAS (RPI4)"
    },
    {
     "expr": "100 * (\r\n  sum(node_filesystem_size_bytes{job=\"RPI4\", fstype!=\"tmpfs\", fstype!=\"devtmpfs\", fstype!=\"squashfs\"}) - sum(node_filesystem_free_bytes{job=\"RPI4\", fstype!=\"tmpfs\", fstype!=\"devtmpfs\", fstype!=\"squashfs\"})\r\n) / sum(node_filesystem_size_bytes{job=\"RPI4\", fstype!=\"tmpfs\", fstype!=\"devtmpfs\", fstype!=\"squashfs\"})\r\n\r\n",
     "legendFormat": "RPI4"
    },
    {
     "expr": "100 * (\r\n  sum(node_filesystem_size_bytes{job=\"PiKVM\", fstype!=\"tmpfs\", fstype!=\"devtmpfs\", fstype!=\"squashfs\"}) - sum(node_filesystem_free_bytes{job=\"PiKVM\", fstype!=\"tmpfs\", fstype!=\"devtmpfs\", fstype!=\"squashfs\"})\r\n) / sum(node_filesystem_size_bytes{job=\"PiKVM\", fstype!=\"tmpfs\", fstype!=\"devtmpfs\", fstype!=\"squashfs\"})\r\n",
     "legendFormat": "PiKVM"
    }
   ]
  },
  {
   "title": "Disk Temperature (ºC)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    { "expr": "hwi_drive_temperature_c", "legendFormat": "{{source}}" }
   ]
  },
  {
   "title": "Drive Health Status (%)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hwi_drive_remaining_life", "legendFormat": "{{source}}" }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    { "expr": "hwi_drive_read_rate_mbs", "legendFormat": "{{source}} Read" },
    { "expr": "hwi_drive_write_rate_mbs", "legendFormat": "{{source}} Write" }
   ]
  },
  {
   "title": "Bandwidth Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    { "expr": "hwi_network_up_rate_kbs * 1024", "legendFormat": "{{source}} Upload" },
    { "expr": "hwi_network_dl_rate_kbs * 1024", "legendFormat": "{{source}} Download" }
   ]
  }
 ]
}